Add links and explanations around Secure by Design principles
DFE-Digital/technical-guidance pull request #206
Opened 2024-12-18 15:37 UTC by pritchyspritch

2024-12-18 17:13 UTC, hannahvb requested changes

2024-12-18 17:13 UTC, hannahvb commented on source/principles/secure-by-design-principles/index.html.md.erb
> +From January, any project delivering changes to digital services or technology infrastructure that is in scope of the [digital and technology spend controls approval process](https://www.gov.uk/gover
Secure by Design can be shortened to 'SbD' throughout this paragraph here as we've used it in line 8.
Do we think we need to spell out CIS for this? I'm not sure if internal people will know off the bat.

2024-12-18 17:13 UTC, hannahvb commented on source/principles/secure-by-design-principles/index.html.md.erb
> +If your project is in scope for Secure by Design, contact the SbD delivery team at the [Secure by Design support channel on Slack](https://ukgovernmentdfe.slack.com/archives/C081Q6S91FB).
Secure by Design to SbD

2024-12-18 17:13 UTC, hannahvb commented on source/principles/secure-by-design-principles/index.html.md.erb
> +In order to assist you and your team with compliance to Secure by Design, you can view [the DfE SbD documentation](https://secure-by-design.security.education.gov.uk/) which is being regularly update
Replace 'in order to assist you and your team' with 'to help you and your team with compliance to...'

2024-12-31 09:16 UTC, saliceti approved these changes

2025-01-06 13:03 UTC, merged